# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: NAFNet-OCL-plain
model_type: ImageRestorationModel
scale: 1
num_gpu: 8
manual_seed: 10

datasets:
  train:
    name: LF2016_OCL
    type: DataLoaderCenterViewsAndShiftToDefocusMap
    dataroot_path: /newDisk/dataset/2x2_OCL_BOKEH/stanford_LF2016
    test_list: LF2016_test_files.json

    img_height: 368
    img_width: 528
    random: true
    crop: true
    ltm: false 
    gamma: 1.0
    size: 5000

    # dataloader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 7
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: LF2016_OCL
    type: DataLoaderCenterViewsAndShiftToDefocusMap
    dataroot_path: /newDisk/dataset/2x2_OCL_BOKEH/stanford_LF2016
    test_list: LF2016_test_files.json

    img_height: 368
    img_width: 528
    random: true
    crop: true
    ltm: false 
    gamma: 1.0
    size: 5000



network_g:
  in_channels: 15
  out_channels: 1
  type: NAFNetPlain
  width: 32
  enc_blk_nums: [2, 2, 4, 8]
  middle_blk_num: 12
  dec_blk_nums: [2, 2, 2, 2]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~
  automatic_resume: false

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: 0.
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 400000
    eta_min: !!float 1e-7

  total_iter: 2500 #500 epochs
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: MSELoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: 50 #every 10 epochs
  save_img: false
  use_image: false
  with_metrics: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
    lpips:
      type: calculate_lpips

# logging settings
logger:
  print_freq: 5 #every epoch
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
